Графика всех страниц
htmlacademy-htmlcss/1019601-sedona-30 pull request #5
Opened 2021-02-07 15:49 UTC by 9fox-kitsune

Разместила изображения в подпапке img; подключила контентные изображения в разметке, а также к проекту фавиконки.

2021-02-07 21:28 UTC, SidSpears69 requested changes

2021-02-07 21:28 UTC, SidSpears69 commented on catalog.html
> +                <img src="img/catalog/checkbox-on.svg" width="20" height="20" alt="pool-on">
Это впоследствии заменится на css, картинки тут не нужны

2021-02-07 21:28 UTC, SidSpears69 commented on catalog.html
> +              <img src="img/catalog/star.svg" width="20" height="20" alt="Star">
Alt "star" не понятен для пользователя, лучше его вообще не использовать, а сделать текст с оценкой и спрятать visual-hidden

2021-02-07 21:28 UTC, SidSpears69 commented on index.html
> +      <img src="img/index/sedona.jpg" height="250" alt="Sedona">
Пропущен width и ниже тоже

2021-02-08 02:10 UTC, 9fox-kitsune commented on catalog.html
> +              <img src="img/catalog/star.svg" width="20" height="20" alt="Star">
то есть картинки не использовать тут и вообще удалить? текст с оценкой - это само название гостиницы чтоб было с оценкой?

2021-02-08 07:30 UTC, SidSpears69 commented on catalog.html
> +              <img src="img/catalog/star.svg" width="20" height="20">
Alt все таки нужен, иначе код будет невалидным, нужно оставить пустым
Пример
```
<p>
<img src="img/catalog/star.svg" width="20" height="20" alt="">
<img src="img/catalog/star.svg" width="20" height="20" alt="">
<img src="img/catalog/star.svg" width="20" height="20" alt="">
<img src="img/catalog/star.svg" width="20" height="20" alt="">
<img src="img/catalog/star.svg" width="20" height="20" alt="">
<span class="visually-hidden">Рейтинг 5 из 5</span>
</p>
```
br под рейтингом лишний

2021-02-08 07:30 UTC, merged